keys:
  - &admin B054287D42FC91AD36137D9F03ECA132FD38CD59
  - &smb age1n8ukjh0krslvv3v5cqy6v5t5utgspek2g3kx3j0gxjszvszllaasllc3hk
  - &surface age1k7dljw9mthfr8y6c99hrkn2ncs0f4dfsm5e42fvfat70wvd7e48qhz0dzl
  - &nebula-lighthouse age109w25c2fjtv2wslwy8hvsms4r6hjmrkfucq2mysskz6wg5jg5s7ql98tzn
  - &r-desktop age1pkwflrjlcf494fcc48rqmcnf0xq5as0ly6w95leq350r9tk4pg8qutw0sc
  - &ssl-proxy age1m0g3qdsn5zanqckt5pt9twm2c7l775uw9ac9rl95xmws8j09hd7sup5zpa
  - &jasmine-laptop age124h0tx68mcsg9q4cfujl2yxd6vpvshrsvwf29u2x0yer0egt9exs5fmjhj
  - &audiobooks age1lywvqnrhwlcnwhw34ry02thte2jatguz5wcq63gymphn9tn47uds0t9dr9
  - &nextcloud age1fk7kw7s2jng3v7dzm0vrq4ccsu9xwtssj2u2evjdsrz4jksngf4sp0knmp
  - &rescueIso age1sr0p82j6yr7s0rs0zck20qau86w4rgd7enkcsg8ud20h9z5nyc8q8jpa4c
  - &petronillaStreaming age1psj4h28ulrglqe48qs3mhchlvvvpx9ew6qy7nve5j5uvvsy80a6shqr20a
creation_rules:
  - path_regex: ^secrets/surface-raoul-nixos/.*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *surface
  - path_regex: ^secrets/nebula-lighthouse/.*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *nebula-lighthouse
  - path_regex: ^secrets/r-desktop/.*$
    key_groups:
      - pgp:
        - *admin
        age:
        - *r-desktop
  - path_regex: ^secrets/smb/.*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *smb
  - path_regex: ^secrets/ssl-proxy/.*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *ssl-proxy
  - path_regex: ^secrets/audiobooks/.*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *audiobooks
  - path_regex: ^secrets/[^/]*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *surface
      - *nebula-lighthouse
      - *r-desktop
      - *ssl-proxy
      - *jasmine-laptop
      - *nextcloud
      - *rescueIso
      - *petronillaStreaming
  - path_regex: ^secrets/jasmine-laptop/.*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *jasmine-laptop
  - path_regex: ^secrets/nextcloud/.*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *nextcloud
  - path_regex: ^secrets/rescueIso/.*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *rescueIso
  - path_regex: ^secrets/petronillaStreaming/.*$
    key_groups:
    - pgp:
      - *admin
      age:
      - *petronillaStreaming
  - path_regex: secrets/bacula/clients/r-desktop.yaml
    key_groups:
    - age:
      - *nextcloud
      - *r-desktop
      pgp:
      - *admin
  - path_regex: secrets/bacula/clients/surface.yaml
    key_groups:
    - age:
      - *surface
      - *nextcloud
      pgp:
      - *admin
  - path_regex: ^secrets/bacula/clients.*
    age: *nextcloud
    pgp: *admin
  - path_regex: ^secrets/
    pgp: *admin
