{ config, pkgs, modulesPath, ... }:

{

  imports = [
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  time.timeZone = "Europe/Berlin";

  proxmoxLXC.manageNetwork = true;
  networking = {
    useDHCP = false;
    useHostResolvConf = false;
    useNetworkd = true;
    # pick up hostname from /etc/hostname generated by proxmox
    hostName = "packete";
  };

  environment.systemPackages = [
    pkgs.apacheHttpd
  ];
  services.httpd = {
    enable = true;
    adminAddr = "webmaster@honermann.info";
    virtualHosts.packete = {
      hostName = "packete.honermann.info";
      documentRoot = "/var/www/packete";
    };
  };
  system.stateVersion = "23.11";

  systemd.tmpfiles.rules = [
    "d ${config.services.httpd.virtualHosts.packete.documentRoot} 1777 1000 1000 "
  ];

  fileSystems."/export/packete" = {
    device = "${config.services.httpd.virtualHosts.packete.documentRoot}";
    options = [ "bind" ];
  };

  services.nfs.server = {
    enable = true;
    exports = ''
      /export/packete 192.168.2.29/23(rw,sync,no_subtree_check,no_root_squash,anonuid=0,anongid=0)
    '';
    lockdPort = 4001;
    mountdPort = 4002;
    statdPort = 4000;
  };


  system.autoUpgrade.flake = "github:RaHoni/nixos-conf";
  system.autoUpgrade.enable = true;

  networking.firewall = {
    enable = true;
    # for NFSv3; view with `rpcinfo -p`
    allowedTCPPorts = [ 111 2049 4000 4001 4002 20048 80 ];
    allowedUDPPorts = [ 111 2049 4000 4001 4002 20048 ];
  };

}
