on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: jimbloemkolk/auto-rebase@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter: always
