name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - ready_for_review
    branches:
      - main
      - dev
  workflow_dispatch:


jobs:
  check:
    runs-on: x86_64-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run check
        run: "nix -L flake check --accept-flake-config"
  merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [ check ]
    if: |
      contains( github.event.pull_request.labels.*.name, 'auto-merge') &&
      !github.event.pull_request.draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Merge if current and checks passed
        run: |
          LATEST_COMMIT=$(gh pr view ${{ github.event.pull_request.number }} --json headRefOid -q .headRefOid)
          if [[ "$LATEST_COMMIT" != "${{ github.event.pull_request.head.sha }}" ]]; then
            echo "Not the latest commit in PR. Skipping merge."
            exit 0
          fi

          # Get the status of required checks
          CHECKS_STATUS=$(gh pr view ${{ github.event.pull_request.number }} --json mergeStateStatus -q .mergeStateStatus)
          sleep 4
          CHECKS_STATUS=$(gh pr view ${{ github.event.pull_request.number }} --json mergeStateStatus -q .mergeStateStatus)
          if [[ "$CHECKS_STATUS" != "CLEAN" ]]; then
            echo $CHECKS_STATUS
            echo "Not all required checks have passed. Skipping merge."
            exit 0
          fi

          git branch -vv
          git merge --ff-only origin/${{ github.event.pull_request.head.ref }}
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

