name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - ready_for_review
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  check:
    runs-on: x86_64-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run check
        run: "nix -L flake check --accept-flake-config"
  merge:
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [ check ]
    if: |
      contains( github.event.pull_request.labels.*.name, 'auto-merge') &&
      !github.event.pull_request.draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Auto Merge
        run: |
          git branch -vv
          git merge --ff-only origin/${{ github.event.pull_request.head.ref }}
          git push
