name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: x86_64-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run check
        run: "nix -L flake check --accept-flake-config"
